//opencv
#include "opencv2/imgcodecs.hpp"
#include "opencv2/imgproc.hpp"
#include "opencv2/videoio.hpp"
#include <opencv2/highgui.hpp>
#include <opencv2/video.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/video/background_segm.hpp>
#include "opencv2/imgcodecs.hpp"
#include "opencv2/imgproc.hpp"
//C
#include <opencv2/core/core.hpp>
#include <stdio.h>
//C++
#include <iostream>
#include <sstream>
#include <unistd.h>
#include <string.h>
using namespace cv;
using namespace std;
bool roi_captured = false;
bool got_roi = false;
Point pt1, pt2;
Mat cap_img;
VideoWriter vw;
Mat fgMaskMOG2; //fg mask fg mask generated by MOG2 method
Ptr<BackgroundSubtractor> pMOG2; 
//Callback for mousclick event, the x-y coordinate of mouse button-up and button-down 
//are stored in two points pt1, pt2.
void mouse_click(int event, int x, int y, int flags, void *param)
{

    switch(event)
    {
        case CV_EVENT_LBUTTONDOWN:
        {
            std::cout<<"Mouse Pressed"<<std::endl;

            if(!roi_captured)
            {
                pt1.x = x;
                pt1.y = y;
            }
            else
            {
                std::cout<<"ROI Already Acquired"<<std::endl;
            }
        break;
        }
        case CV_EVENT_LBUTTONUP:
        {
          if(!got_roi)
        {
            Mat cl;
            std::cout<<"Mouse LBUTTON Released"<<std::endl;

            pt2.x = x;
            pt2.y = y;
            cl = cap_img.clone();
            Mat roi(cl, Rect(pt1, pt2));
            Mat prev_imgT = roi.clone();
            std::cout<<"PT1"<<pt1.x<<", "<<pt1.y<<std::endl;
            std::cout<<"PT2"<<pt2.x<<","<<pt2.y<<std::endl;

            imshow("Clone",cl);

            got_roi = true;
        }
        else
        {
            std::cout<<"ROI Already Acquired"<<std::endl;
        }
        break;  
        }

    }

}
//In main open video and wait for roi event to complete by the use.
// You capture roi in pt1 and pt2 you can use the same coordinates for processing // //subsequent frame
int main(int argc, char *argv[])
{
    int frame_num = 0;
    int non_decode_frame =0;
    int count = 1, idx =0;
    int frame_pos =0;

//    std::cout<<"Video File "<<argv[1]<<std::endl;
   
    std::string seq("IM-4560-0001.png");
     
    //cv::VideoCapture input_video(argv[1]);
    cv::VideoCapture sequence(seq);

    namedWindow("My_Win",1);

    cvSetMouseCallback("My_Win", mouse_click, 0);

    sleep(1);
    pMOG2 = createBackgroundSubtractorMOG2();
    //while(input_video.grab())
    vw = VideoWriter();	
    vw.open("seq_vid.avi", CV_FOURCC('X','V','I','D'), 30, cv::Size (230,256), true);
    for(;;)
    {
        cap_img.release();
    //    cap_img=seq;
	sequence >> cap_img;
	if(cap_img.empty())
	{
	   cout<<"End of sequence"<<endl;
	   break;
	}
        //if(input_video.retrieve(cap_img))
	else
        {
	    vw.write(cap_img);
            imshow("My_Win", cap_img);
            if(!got_roi)
            {
                            //Wait here till user select the desire ROI
                waitKey(0);
            }
            else
            {
                std::cout<<"Got ROI disp prev and curr image"<<std::endl;
                std::cout<<"PT1"<<pt1.x<<" "<<pt1.y<<std::endl;
                std::cout<<"PT2"<<pt2.x<<" "<<pt2.y<<std::endl;
			
		
                Mat curr_img_t1;
                Mat roi2(cap_img,Rect(pt1, pt2));
                Mat curr_imgT = roi2.clone();
                //cvtColor(curr_imgT, curr_img_t1, CV_RGB2GRAY);
       		pMOG2->apply(curr_imgT, fgMaskMOG2);
        	//get the frame number and write it on the current frame
        	stringstream ss;
        	rectangle(curr_imgT, pt1,pt2,
                cv::Scalar(255,255,255), -1);
        	ss << vw.get(CAP_PROP_POS_FRAMES);
        	string frameNumberString = ss.str();
        	putText(curr_imgT, frameNumberString.c_str(), cv::Point(15, 15),
                FONT_HERSHEY_SIMPLEX, 0.5 , cv::Scalar(0,0,0));
       		//how the current frame and the fg masks
        	imshow("Frame", curr_imgT);
        	imshow("FG Mask MOG 2", fgMaskMOG2);
//		vw = VideoWriter();			
            	// Do remaining processing here on capture roi for every frame
//		if(vw.isOpened())
//			std::cout<<"VW Opened\n";
                               waitKey(30);
                        }
                  }
}
vw.release();
}
